version: '3.3'
services:
  backend:
    container_name: backend
    build: .
    image: backend:latest
    restart: always
    ports:
      - "8000:80"

networks:
  default:
    external:
      name: proxy
